* Thoughts about things to try:
** CMH Parking initial thoughts
*** When and where?
- issued the most or least?
- is there a good or bad time of the day to park for < 30 minutes without getting a
  ticket?
- where are the most expensive or least expensive tickets given?
*** Are certain meters less likely to get checked?
- zones that don't get tickets as much.. is it that enforcement is lax or are people more
  likely to pay for parking?
- if there's a regular pattern in how meters are checked, then perhaps some meters may be
  very likely to not be checked for a period of time.
*** Enforcement and social status / neighborhood
- Are rich or poor areas more or less likely to be checked?
*** Are there better ways to enforce parking?
If there are patterns of poor enforcement, how can enforcement be made more even?
*** Other data sources?
What else can be brought in to this?
- If we know what events happened, when and where we may be able to correlate that with parking
  violations?
- Is there a way for someone to know where there's most likely to be available parking at
  a particular time or location?  Not sure what data could be brought in to help with that..
* OSX installation notes
- It works with python 3.7.6.  When using python 3.8 had an issue when installing
  scikit-learn, so sticking with 3.7 for now.
* Working with Git
Notebooks in the default .ipynb format (JSON) save the execution output for each block so
that it's easier to share the results with others.

Unfortunately this format makes it hard to see what's changed from one commit to another,
which is a particularly big issue if you want to collaborate with others on a notebook.

The solution I landed on is: https://github.com/mwouts/jupytext.  Essentially you edit the
python code as a python file (with .py extension) and you can set up jupyer to also create
a .ipynb file alongside the python file.  This way you get the best of both worlds: diff
they python file to see what's changed but also have the full-blown output to share with
others. 

