
* Explore Parking Violations in Columbus, OH
We are using data from SmartColumbus

** Jupyter notebook
The jupyter notebook we are using is: notebooks/Cmh_Parking_Violation.ipynb.  The violations and
meter data have already been downloaded in the data/raw directory.  For the dictionary of terms
used by violations we reach out to get it every time, but we could save that too.

** OSX installation notes
- It works with python 3.7.6.  When using python 3.8 had an issue when installing
  scikit-learn, so sticking with 3.7 for now.

** Working with Git
Notebooks in the default .ipynb format (JSON) save the execution output for each block so
that it's easier to share the results with others.

Unfortunately this format makes it hard to see what's changed from one commit to another,
which is a particularly big issue if you want to collaborate with others on a notebook.

One solution I am exploring is: https://github.com/mwouts/jupytext.  Essentially you edit the
python code as a python file (with .py extension) in an external editor and you can set up jupyer to
also sync it up a .ipynb file alongside the python file.  The plugin will let you open the .py file as
a notebook, and it keeps the .ipynb file up-to-date.

Theoretically you get the best of both worlds: edit files in a real editor with refactor capabilities,
get the ability to diff the python file to see what's changed in git,  but also have the full-blown output
in the .ipynb file to share with others.

Main issue I see is: if you edit the python file in the browser through jupyter-notebook it still
makes the diff a little odd, so you might need some discipline to edit mostly in external editor.

I like Pycharm, but I think that one requires a license.

** Initial thoughts about things to try:
*** CMH Parking initial thoughts
**** When and where?
- issued the most or least?
- is there a good or bad time of the day to park for < 30 minutes without getting a
  ticket?
- where are the most expensive or least expensive tickets given?
**** Are certain meters less likely to get checked?
- zones that don't get tickets as much.. is it that enforcement is lax or are people more
  likely to pay for parking?
- if there's a regular pattern in how meters are checked, then perhaps some meters may be
  very likely to not be checked for a period of time.
**** Enforcement and social status / neighborhood
- Are rich or poor areas more or less likely to be checked?
**** Are there better ways to enforce parking?
If there are patterns of poor enforcement, how can enforcement be made more even?
**** Other data sources?
What else can be brought in to this?
- If we know what events happened, when and where we may be able to correlate that with parking
  violations?
- Data about parking utilization could be useful in conjunction with violations.
